Proactive.Admin/Controllers/InfringementController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Proactive.Admin.Filters;
using Proactive.Core.Enumerations;
using Proactive.Core.Helper;
using Proactive.Core.Models;
using Proactive.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Proactive.Admin.Controllers
{
    [CustomAuthorization(Role.Admin, Role.Client)]
    public class InfringementController : ApplicationBaseController
    {
        private readonly InfringementService _service;

        public InfringementController()
        {
            _service = new InfringementService();
        }

        public ActionResult Index()
        {
            BindList();
            InfringementListWithFilter model = new InfringementListWithFilter();
            IQueryable<InfringementViewModel> obj = _service.GetInfringement();
            model.InfringementView = obj;
            return View(model);
        }

        public void ExportInfringementData()
        {
            IQueryable<InfringementViewModel> obj = _service.GetInfringement();
            WebGrid grid = new WebGrid(source: obj, canPage: false, canSort: false);
            string gridData = grid.GetHtml(
            columns: grid.Columns(
                grid.Column("Platform", "Platform"),
                grid.Column("Country", "Country"),
                grid.Column("Title", "Title"),
                grid.Column("Url", "Url"),
                grid.Column("Price", "Price"),
                grid.Column("Quantity", "Quantity"),
                grid.Column("ItemNumber", "ItemNumber"),
                grid.Column("SellerLocation", "SellerLocation"),
                grid.Column("InfringementType", "InfringementType"),
                grid.Column("Remark", "Remark"),
                grid.Column("ItemLocation", "ItemLocation"),
                grid.Column("ClientName", "ClientName"),
                grid.Column("ReviewStatus", "ReviewStatus")
                )).ToString();
            Response.ClearContent();

            Response.AddHeader("content-disposition", "attachment; filename=Infringement.xls");

            Response.ContentType = "application/excel";

            Response.Write(gridData);

            Response.End();
        }

        public ActionResult AllInfringement()
        {
            BindList();
            InfringementListWithFilter model = new InfringementListWithFilter();
            var UserId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetInfringement(UserId);
            model.InfringementView = objData;
            return View("AllInfringements", model);
        }

        public void ExportClientInfringementData()
        {
            var UserId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> obj = _service.GetInfringement(UserId);
            WebGrid grid = new WebGrid(source: obj, canPage: false, canSort: false);
            string gridData = grid.GetHtml(
            columns: grid.Columns(
                grid.Column("InfringementId", "InfringementId"),
                grid.Column("Platform", "Platform"),
                grid.Column("Country", "Country"),
                grid.Column("Title", "Title"),
                grid.Column("Url", "Url"),
                grid.Column("Price", "Price"),
                grid.Column("Quantity", "Quantity"),
                grid.Column("ItemNumber", "ItemNumber"),
                grid.Column("SellerLocation", "SellerLocation"),
                grid.Column("InfringementType", "InfringementType"),
                grid.Column("Remark", "Remark"),
                grid.Column("ItemLocation", "ItemLocation"),
                grid.Column("ClientName", "ClientName"),
                grid.Column("ReviewStatus", "ReviewStatus"),
                grid.Column("IsSendForRview", "IsSendForRview")
                )).ToString();
            Response.ClearContent();

            Response.AddHeader("content-disposition", "attachment; filename=ClientInfringement.xls");

            Response.ContentType = "application/excel";

            Response.Write(gridData);

            Response.End();
        }



        public ActionResult AllInfringementReview()
        {
            var UserId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetInfringementReview(UserId);
            return View(objData);
        }

        public ActionResult Accepted()
        {
            var UserId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetInfringementApprove(UserId);
            return View("InfringementAccepted", objData);
        }

        public ActionResult Retract()
        {
            var UserId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetInfringementRetract(UserId);
            return View("InfringementRetract", objData);
        }

        public ActionResult Rejected()
        {
            var UserId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetInfringementReject(UserId);
            return View("InfringementRejected", objData);
        }

        public ActionResult Closed()
        {
            ViewBag.action = "Closed";
            InfringementListWithFilter model = new InfringementListWithFilter();
            var UserId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetInfringementByStatus(ReviewStatus.Close, UserId);
            return View("InfringmentClosed", objData);
        }

        public ActionResult Opened()
        {
            ViewBag.action = "Reported";
            var UserId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetInfringementByStatus(ReviewStatus.Open, UserId);
            return View("InfringmentClosed", objData);
        }

        [HttpPost]
        public PartialViewResult InfringementByFilter(InfringementListWithFilter model)
        {
            IQueryable<InfringementViewModel> objData = _service.GetInfringementByFilter(model.InfringementFilter);
            return PartialView("_infringementFilter", objData);
        }

        [HttpPost]
        public PartialViewResult ClientInfringementByFilter(InfringementListWithFilter model)
        {
            string clientid = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetClientInfringementByFilter(model.InfringementFilter, clientid);
            return PartialView("_infringementFilterClient", objData);
        }

        [HttpPost]
        public PartialViewResult InfringementViewall()
        {
            IQueryable<InfringementViewModel> objData = _service.GetInfringement();
            return PartialView("_infringementFilter", objData);
        }

        [HttpPost]
        public PartialViewResult ClientInfringementViewall()
        {
            string userId = User.Identity.GetUserId();
            IQueryable<InfringementViewModel> objData = _service.GetInfringement(userId);
            return PartialView("_infringementFilter", objData);
        }

        public async Task<ActionResult> Add()
        {
            BindList();
            BindSeller();
            InfringementAddModel model = new InfringementAddModel();
            return View("AddorUpdate", model);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int Id)
        {
            InfringementAddModel model = await _service.GetInfringement(Id);
            if (model != null)
            {
                BindList();
                BindSeller();
                return View("AddorUpdate", model);
            }

            OnBindMessage(AlertStatus.Danger, "Resource can't be found");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<ActionResult> Add(InfringementAddModel model)
        {
            if (ModelState.IsValid)
            {
                model.UserId = User.Identity.GetUserId();
                ResponseModel<object> mResult = await _service.AddorUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);
                if (mResult.Status == ResponseStatus.Success)
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                OnBindMessage(AlertStatus.Danger, "please enter all required filed!");
                BindList();
            }
            return View("AddorUpdate", model);
        }

        [HttpPost]
        public async Task<ActionResult> AddCeaseAndDesist(string CeaseselectedInfringementIds, string chkCloseInfringement, string txtSource)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];
                //get filename
                string ogFileName = file.FileName.Trim('\"');
                string shortGuid = ShortGuid.NewGuid().ToString();
                var thisFileName = shortGuid + Path.GetExtension(ogFileName);

                file.SaveAs(Path.Combine(GlobalConfig.CeaseAndDesistPath, thisFileName));
                mResult = await _service.AddUpdateCeaseAndDesist(thisFileName, CeaseselectedInfringementIds, chkCloseInfringement, txtSource);
                OnBindMessage(mResult.Status, mResult.Message);
            }
            else
            {
                OnBindMessage(AlertStatus.Danger, "Please upload document!");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]

Proactive.Admin/Views/Infringement/Infrigments.cshtml
@model IEnumerable<InfringementViewModel>
@{
    ViewBag.Title = "Infrigments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    ViewBag.Title = "Inquiry";
}

@Styles.Render("~/css/viewgrid")
@section Scripts {
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    @Scripts.Render("~/jquery/viewgrid")
    <script type="text/javascript">
        ActiveMenu("Infringment")

        //function convertToDate(data) {
        //    var dtStart = new Date(parseInt(data.substr(6)));
        //    var dtStartWrapper = moment(dtStart);
        //    return dtStartWrapper.format("DD/MMM/YYYY");
        //}

        $(document).ready(function () {
            $('#datatable').DataTable({
                scrollX: true,
                proccessing: true,
                serverSide: true,
                autoWidth: false,
                responsive: true,
                sortable: false,
                searchable: false,

                fixedHeader: {
                    header: true,
                    headerOffset: $('.header-navbar').outerHeight()
                },
                language: {
                    search: "",
                    searchPlaceholder: "Search..."
                },
                ajax: {
                    url: "@Url.Action("Infrigments", "Infringement")",
                    type: 'POST',
                },
                columns:
                    [
                        { data: "InfringementId", title: "Id" },
                        { data: "Platform", title: "Site" },
                        { data: "Title", title: "Url" },
                        { data: "Price", title: "Quantity" },
                        { data: "SellerLocation", title: "Seller Location" },
                        { data: "ItemLocation", title: "Seller" },
                        { data: "ItemNumber", title: "ItemNumber" },
                        { data: "ClientName", title: "ClientName" },
                        { data: "InfringementType", title: "InfringementType" },
                        { data: "ReviewStatus", title: "ReviewStatus" },
                        { data: "CeaseandDesistImageList", title: "CeaseandDesistImageList" },
                        { data: "Url", title: "Url" },
                        { data: "Remark", title: "Remark" },
                        {
                            data: null,
                            title: "Action",
                            sortable: false,
                            searchable: false,
                            orderable: false,
                            mRender: function (x) {
                                return BindActionButtons(x.Id);
                            }
                        }
                    ]
            });
        });

        function BindActionButtons(Id) {
            var strButtons = '';
            var strButton2 = '';
            //Delete button
            strButtons += '<button type="button" onclick="deleteRow($(this))"';
            strButtons += 'class="btn btn-sm btn-primary btn-red ml-1"';
            strButtons += 'data-id="' + Id + '"';
            strButtons += 'data-url="@Url.Action("Delete")"';
            strButtons += '>';
            strButtons += '<i class="fa fa-trash"></i> Delete';
            strButtons += '</button>';

            strButton2 += '<button type="button" onclick="deleteRow($(this))"';
            strButton2 += 'class="btn btn-sm btn-primary btn-blue ml-1"';
            strButton2 += 'data-id="' + Id + '"';
            strButton2 += 'data-url="@Url.Action("Edit")"';
            strButton2 += '>';
            strButton2 += '<i class="fa fa-trash"></i> Edit';
            strButton2 += '</button>';

            strButtons += '<br/><br/>' + strButton2
            return strButtons;
        }
    </script>
}

<div class="row">
    <div class="col-12">
        <div class="card box-shadow-0 border-info border-bottom-3">
            <div class="card-header card-head-inverse bg-info">
                <h4 class="card-title text-white">
                    <i class="fa fa-fw fa-cogs"></i>&nbsp;Manage Infregment
                </h4>
                <a class="heading-elements-toggle">
                    <i class="fa fa-ellipsis-v fa-fw font-medium-3"></i>
                </a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li>
                            <a data-action="collapse">
                                <i class="fa fa-minus fa-fw"></i>
                            </a>
                        </li>
                        <li>
                            <a data-action="expand">
                                <i class="fa fa-window-maximize fa-fw"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card-content show">
                <div class="card-body">
                    <table class="table table-striped table-bordered datatable" id="datatable">
                        <thead>
                            <tr>
                                <th rowspan="2"></th>
                                <th>Plateform</th>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Item</th>
                                <th>Salary</th>
                            </tr>
                            <tr>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Proactive.Admin/Views/Infringement/InfringementRejected.cshtml
@model IQueryable<InfringementViewModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Rejected Infringement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")
@helper ViewImage(string imageUrl)
{
    <img src="@imageUrl" width="50px" />
}
@helper ViewDetails(string Title, string URLink)
{
    @Title
    <br />
    <a href=@Url.Action(URLink) target="_blank">@URLink</a>
}
@helper GetCheckBox(int InfringementId)
{
    <input type="checkbox" data-id="@InfringementId" class="chk-group slectInfringementId" />
}
@helper ViewFile(List<CeaseandDesistImagesModel> File)
{
    foreach (var item in File)
    {
        <a href="@item.imageUrl" target="_blank">View File</a>
        <br />
    }
}
@helper ViewPlatform(string Platform, string Site)
{
    @Platform
    <br />
    @Site
}
@helper ViewTitle(string Title, string URLink)
{
    @Title
    <br />
    <a href="@Url.Content(URLink)" targ target="_blank">Open Link</a>
}
@helper ViewGallary(List<ImagesModel> Urls)
{
    foreach (var item in Urls)
    {
        <img src=@Url.Content(item.imageUrl) height="50px" width="50px" />
        <br />
    }
}

@helper ViewPrice(double Price, int Quantity)
{
    @Price
    <br />
    @Quantity
}
@helper ViewItem(string Item, string seller)
{
    @Item
    <br />
    @seller
}
@helper ViewItemLocation(string ItemLocation, string sellerlocation)
{
    @ItemLocation
    <br />
    @sellerlocation
}
@helper ViewInfrigmentType(string InfrigmentType, string Remark)
{
    @InfrigmentType
    <br />
    @Remark
}
@helper ViewCeaseandDesist(List<CeaseandDesistImagesModel> File)
{
    foreach (var item in File)
    {
        <text>@item.Source</text>
        <a href="@item.imageUrl" target="_blank">View File</a>
        <br />
    }
}

@helper ViewDates(DateTime Reported, DateTime? Updated)
{
    @Reported
    <br />
    @Updated
}

@helper ActionButtons(int Id)
{
    <a href="javascript:;" data-id="@Id" data-toggle="modal" @*data-target="#fp_Modal"*@
       data-whatever=""
       class="btn btn-sm btn-primary btn-red Reject">
        <i class="icon-ban"></i> Retract
    </a>
}

@*@helper ActionButtons(int Id)
    {
        <a href="javascript:;" class="btn btn-sm btn-primary btn-red Reject" data-id="@Id">
            <i class="icon-ban"></i> Reject
        </a>

        <a href="javascript:;" class="btn btn-sm btn-primary btn-green Accept" data-id="@Id">
            <i class="icon-checkmark"></i> Accept
        </a>
    }*@
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card box-shadow-0 border-primary">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">Rejected Infringement</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            @*<li>
                                    <input type="checkbox" id="select_all" class="form-control chk-all" /> &nbsp; &nbsp;Select All&nbsp;&nbsp;
                                </li>*@
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add(x=>x.Platform).Titled(Html.Raw("Plateform <br/><hr> Site").ToString()).Encoded(false).Sanitized(false).RenderValueAs(x => ViewPlatform(x.Platform, x.Country));

                               column.Add(x=>x.Title).Titled(Html.Raw("Title <br/><hr> Url").ToString()).Encoded(false).Sanitized(false).RenderValueAs(x => ViewTitle(x.Title, x.Url));

                               column.Add(x=>x.imageList).Titled("Gallery").Encoded(false).Sanitized(false).RenderValueAs(x => ViewGallary(x.imageList));

                               column.Add(x=>x.Price).Titled(Html.Raw(Html.Raw("Price <br/><hr> Quantity").ToString()).ToString()).Encoded(false).Sanitized(false).RenderValueAs(x => ViewPrice(x.Price, x.Quantity));

                               column.Add(x=>x.ClientName).Titled(Html.Raw("Item <br/><hr> Seller").ToString()).Encoded(false).Sanitized(false).RenderValueAs(x => ViewItem(x.ItemNumber, x.ClientName));

                               column.Add(x=>x.SellerLocation).Titled(Html.Raw("Item <br/><hr> Seller Location").ToString()).Encoded(false).Sanitized(false).RenderValueAs(x => ViewItemLocation(x.ItemLocation, x.SellerLocation));

                               column.Add(x=>x.InfringementType).Titled(Html.Raw("Infrigment Type <br/><hr> Remark").ToString()).Encoded(false).Sanitized(false).RenderValueAs(x => ViewInfrigmentType(x.InfringementType, x.Remark)).SetWidth(200);

                               column.Add(x=>x.CeaseandDesistImageList).Titled("Cease and desist").Encoded(false).Sanitized(false).RenderValueAs(x => ViewFile(x.CeaseandDesistImageList)).SetWidth(200);

                               //column.Add(x => x.ReviewStatus).Titled("Status").Encoded(false).Sanitized(false).SetWidth(100);

                               column.Add(p => p.ReportedTime).Titled(Html.Raw("Reported Time <br/><hr> Removed Time").ToString()).Encoded(false).Sanitized(false).RenderValueAs(x => ViewDates(x.ReportedTime, x.RemovedTime)).SetWidth(300);

                               column.Add().Titled("Action").Encoded(false).Sanitized(false)
                                .RenderValueAs(x => ActionButtons(x.InfringementId));

                           }).Sortable(true).Filterable(true).Selectable(false).WithPaging(GlobalConfig.PageSize_AdminPanel)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="fp_Modal" tabindex="-1" role="dialog" aria-labelledby="fp_ModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="fp_ModalLabel">Reason</h5>
                        </div>
                        @using (Html.BeginForm("RetractByClient", "Infringement", FormMethod.Post, new { @id = "formreason" }))
                        {
                            <div class="modal-body">
                                <p>Reason</p>
                                <div class="form-group">
                                    <input type="hidden" name="InfId" id="InfId" />
                                    <textarea id="reasonText" name="reasonText" placeholder="enter reson" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="button" class="btn" data-dismiss="modal" value="Close">
                                <input type="submit" class="btn btn-md btn-primary" value="Save Changes" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    <script type="text/javascript">
        ActiveMenu("InfringementRejected");
        $(".jsgrid-grid-body").css('overflow-x', 'auto');
    </script>

    <script type="text/javascript">
           $(function () {
               $(".Accept").click(function () {
                var control = $(this);
                var Url = '@Url.Action("CloseInfringement")';

                 swal({
                     title: "Are you sure to Accept this request?",
                     //text: "You will not be able to recover this date!",
                     type: "warning",
                     showCancelButton: true,
                     confirmButtonColor: "#DA4453",
                     CancelButtonColor: "#DA4453",
                     confirmButtonText: "Yes, accept it!",
                     cancelButtonText: "No, cancel plx!",
                     closeOnConfirm: false,
                     closeOnCancel: false
                 }, function (isConfirm) {
                     if (isConfirm) {
                         $.post(Url, { 'id': $(control).attr('data-id'), 'UserID': $(control).attr('data-userid') }, function (response) {
                             if (response.Status == 1) {
                                 control.parent().parent().hide(200);
                                 setTimeout(function () { control.remove() }, 300);
                                 swal("Accepted!", response.Message, "success");

                             }
                             else {
                                 control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-ban');
                                 swal("Error", response.Message, "error");
                             }
                         });
                     } else {
                         control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-ban');
                         swal("Cancelled", "Your record is safe :)", "info");
                     }
                 });
               });

               $(".Reject").click(function () {
                   var control = $(this);
                   var id = control.data('id');
                   $('#InfId').val(id);
                   console.log(id);
                 var Url = '@Url.Action("RetractByClient")';
                 swal({
                     title: "Are you sure to reject this request?",
                     type: "warning",
                     showCancelButton: true,
                     confirmButtonColor: "#DA4453",
                     confirmButtonText: "Yes, reject it!",
                     cancelButtonText: "No, cancel plx!",
                     closeOnConfirm: true,
                     closeOnCancel: false
                 }, function (isConfirm) {
                     if (isConfirm) {
                         $('#fp_Modal').modal();
                         //$.post(Url, { 'id': $(control).attr('data-id'), 'UserID': $(control).attr('data-userid') }, function (response) {
                         //    if (response.Status == 1) {
                         //        control.parent().parent().hide(200);
                         //        setTimeout(function () { control.remove() }, 300);
                         //        swal("Rejected!", response.Message, "success");
                         //    }
                         //    else {
                         //        control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-toggle-right');
                         //        swal("Error", response.Message, "error");
                         //    }
                         //});
                     } else {
                         control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-toggle-right');
                         swal("Cancelled", "Your record is safe :)", "info");
                     }
                 });
               });



        });
    </script>
}