Proactive.Admin/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proactive.Admin.Controllers
{
    [AllowAnonymous]
    public class ErrorController : Controller
    {
        public ActionResult Index(int errorCode, string errorTitle, string errorDescription)
        {
            ViewBag.errorCode = errorCode;
            ViewBag.errorTitle = errorTitle;
            ViewBag.errorDescription = errorDescription;
            return View();
        }
        public ActionResult NotFound()
        {
            return View();
        }
        public ActionResult BadRequest(string errorTitle, string errorDescription)
        {
            ViewBag.errorTitle = errorTitle;
            ViewBag.errorDescription = errorDescription;
            return View();
        }
        public ActionResult ServerError(string errorTitle, string errorDescription)
        {
            ViewBag.errorTitle = errorTitle;
            ViewBag.errorDescription = errorDescription;
            return View();
        }
        public ActionResult Unauthorized()
        {
            return View();
        }
        public ActionResult InvalidAccess()
        {
            return View();
        }
    }
}

Proactive.Admin/Controllers/ResourceController.cs
using Proactive.Admin.Filters;
using Proactive.Core.Enumerations;
using Proactive.Core.Helper;
using Proactive.Core.Models;
using Proactive.Data.Repository;
using Proactive.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Proactive.Admin.Controllers
{
    [CustomAuthorization(Role.Admin, Role.Client)]
    public class ResourceController : ApplicationBaseController
    {
        private readonly BrandServices _service;

        public ResourceController()
        {
            ResourceType();
            _service = new BrandServices();
        }

        public ActionResult Index()
        {
            return View(_service.GetContentList());
        }

        public ActionResult Add()
        {
            ViewBag.Action = "Add";
            ResourceContentModel model = new ResourceContentModel();
            return View("AddorUpdate", model);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int Id)
        {
            BindCountry();
            ViewBag.Action = "Add";
            var model = await _service.GetContents(Id);
            if (model != null)
            {
                return View("AddorUpdate", model);
            }
            OnBindMessage(AlertStatus.Danger, "Resource can't be found");
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Add(ResourceContentModel model)
        {
            BindClient();
            if (ModelState.IsValid)
            {
                if (model.fileBaseImage != null)
                {
                    string ogFileName = model.fileBaseImage.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.fileBaseImage.SaveAs(Path.Combine(GlobalConfig.BrandImagePath, thisFileName));
                    model.imageName = thisFileName;
                }
                ResponseModel<object> mResult = await _service.AddUpdateBrandProtection(model);
                OnBindMessage(mResult.Status, mResult.Message);
            }
            return RedirectToAction("index");
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int Id)
        {
            ResponseModel<object> mResult = await _service.Delete(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }
    }
}

Proactive.Admin/Controllers/UtilityController.cs
using Proactive.Core.Helper;
using Proactive.Core.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proactive.Admin.Controllers
{
    public class UtilityController : Controller
    {
        public UtilityController()
        {

        }

        [HttpPost]
        public JsonResult UploadCropImage(SaveImageModel model)
        {
            string imageName = Guid.NewGuid().ToString() + "." + model.extension;
            string filePath = Path.Combine(model.saveFilePath, imageName);
            ResponseModel<object> mResult = Utilities.SaveCropImage(model.imgBase64String, filePath, model.extension);
            mResult.Result = imageName;

            if (!string.IsNullOrEmpty(model.previousImageName))
            {
                string ExistFilePath = Path.Combine(model.saveFilePath, model.previousImageName);
                if (System.IO.File.Exists(ExistFilePath))
                {
                    System.IO.File.Delete(ExistFilePath);
                }
            }

            return Json(mResult);
        }
    }
}

Proactive.Admin/Views/Shared/AddorUpdate.cshtml
@model ResourceContentModel
@{
    ViewBag.Title = "AddUpdate";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string _action = ViewBag.Action;

    UploadImageModel objUploadImage = new UploadImageModel() { imageUrl = GlobalConfig.BrandImageUrl + "Default.jpg", saveFilePath = GlobalConfig.BrandImagePath, hdnImageName = "ImageName" };

}
@Styles.Render("~/css/uploadImage")
@Styles.Render("~/css/summernote")
@Styles.Render("~/css/icheck")
<section id="validation">
    <div class="row">
        <div class="col-xs-12">
            @using (Html.BeginForm(_action, "Resource", FormMethod.Post, new { @id = "frmAddInsights", @class = "form-horizontal", @enctype = "multipart/form-data" }))
            {

                @Html.HiddenFor(x => x.Id)
                <div class="card box-shadow-0 border-primary">
                    <div class="card-header card-head-inverse bg-primary">
                        <h4 class="card-title">@ViewBag.TitleName</h4>
                        <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    </div>
                    <div class="card-body collapse in">
                        <div class="card-block">
                            <div class="form-group row">
                                <div class="col-md-6">
                                    <div class="col-md-12">
                                        @Html.Partial("_ImageUpload", new UploadImageModel() { imageUrl = GlobalConfig.BrandImageUrl + Model.imageName, saveFilePath = GlobalConfig.BrandImagePath, hdnImageName = "imageName" })
                                        @Html.HiddenFor(x => x.imageName)
                                        @Html.ValidationMessageFor(x => x.imageName)
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <div class="form-group row">
                                            <div class="col-md-12">
                                                @Html.TextBoxFor(x => x.Title, new { @class = "form-control require", @placeholder = "Enter title here" })
                                                @Html.ValidationMessageFor(x => x.Title)
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-md-12">
                                                @Html.DropDownListFor(x => x.ResourceType, new SelectList(ViewData["ResourceTypeList"] as IEnumerable<SelectListItem>, "Value", "Text"), "Select Page Type", new { @class = "form-control select2Group" })
                                                @Html.ValidationMessageFor(x => x.ResourceType)
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-md-12">
                                                @Html.EnumDropDownListFor(x => x.ContentType, new { @class = "form-control require", @placeholder = "Enter author name" })
                                                @Html.ValidationMessageFor(x => x.ContentType)
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <div class="col-md-12" style="align-content:center">
                                            @Html.TextAreaFor(x => x.Description, new { @class = "form-control require", @placeholder = "Enter content here" })
                                            @Html.ValidationMessageFor(x => x.Description)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <input type="submit" class="btn btn-md btn-primary" value="Save Changes" />
                                <a href="@Url.Action("Index")" class="btn btn-md btn-grey">
                                    Cancel
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/validate")
    @Scripts.Render("~/jQuery/iCheck")
    @Scripts.Render("~/jQuery/summernote")
    @Scripts.Render("~/jQuery/uploadImage")
    <script type="text/javascript">
        ActiveMenu('@Model.ResourceType.ToString()@Model.ContentType.ToString()');
        $(function () {
            $('#Description').summernote({
                height: 200,                 // set editor height
              //  width: 1300,   //don't use px
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: true,
                //toolbar: [
                //    ['style', ['bold', 'italic', 'underline', 'clear']],
                //    ['fontsize', ['fontsize']],
                //    ['color', ['color']],
                //    ['para', ['ul', 'ol', 'paragraph']],
                //    ['height', ['height']],
                //],
            });
        });

    </script>

}

Proactive.Admin/Views/Shared/_Alert.cshtml
@{ AlertModel alertModel = TempData["alertModel"] as AlertModel;
    if (alertModel != null)
    {
        if (!string.IsNullOrEmpty(alertModel.alertMessage))
        {
            <section id="solid-alerts">
                <div class="alert bg-@alertModel.alertStatus.ToString() alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <span id="message">@alertModel.alertMessage</span>
                </div>
            </section>
        }
    }
    else
    {
        <section id="solid-alerts" style="display:none">
            <div class="alert alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <span id="message"></span>
            </div>
        </section>
    }
}

Proactive.Admin/Views/Shared/_Error.cshtml
<!DOCTYPE html>
<html lang="en" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">

    <title>@ViewBag.Title - @GlobalConfig.ProjectName</title>
    <link rel="apple-touch-icon" sizes="57x57" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-57x57.png")">
    <link rel="apple-touch-icon" sizes="60x60" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-60x60.png")">
    <link rel="apple-touch-icon" sizes="72x72" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-72x72.png")">
    <link rel="apple-touch-icon" sizes="76x76" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-76x76.png")">
    <link rel="apple-touch-icon" sizes="114x114" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-114x114.png")">
    <link rel="apple-touch-icon" sizes="120x120" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-120x120.png")">
    <link rel="apple-touch-icon" sizes="144x144" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-144x144.png")">
    <link rel="apple-touch-icon" sizes="152x152" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-152x152.png")">
    <link rel="apple-touch-icon" sizes="180x180" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-180x180.png")">
    <link rel="icon" type="image/png" sizes="192x192" href="@Url.Content("~/Files/DefaultImages/favicon/android-icon-192x192.png")">
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Content("~/Files/DefaultImages/favicon/favicon-32x32.png")">
    <link rel="icon" type="image/png" sizes="96x96" href="@Url.Content("~/Files/DefaultImages/favicon/favicon-96x96.png")">
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Content("~/Files/DefaultImages/favicon/favicon-16x16.png")">
    <link rel="manifest" href="@Url.Content("~/Files/DefaultImages/favicon/manifest.json")">
    <meta name="msapplication-TileColor" content="#005893">
    <meta name="msapplication-TileImage" content="@Url.Content("~/Files/DefaultImages/favicon/ms-icon-144x144.png")">
    <meta name="theme-color" content="#005893">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    @Styles.Render("~/css/bundles")
    <style>
        body * {
            color: #fff !important;
        }
    </style>
</head>
<body data-open="click" data-menu="vertical-content-menu" data-col="1-column" class="vertical-layout vertical-content-menu 1-column bg-danger blank-page blank-page">
    <div class="app-content content container-fluid">
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/jQuery/bundles")
</body>
</html>

Proactive.Admin/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Proactive.Admin/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Proactive.Admin/Views/Shared/_ImageUpload.cshtml
@model UploadImageModel

<style>
    .img-container img.file-crop {
        max-width: 100%;
        max-height: 70vh;
    }
</style>
<div class="form-group">
    <div class="main-img-preview">
        <img class="thumbnail img-preview" id="preview_@Model.hdnImageName" src="@Model.imageUrl" title="Preview Logo">
    </div>
    <div class="input-group">
        <input type="hidden" id="prev_@Model.hdnImageName" />
        <input id="fileFake_@Model.hdnImageName" class="form-control" placeholder="Choose File" disabled="disabled">
        <div class="input-group-btn">
            <div class="fileUpload btn btn-primary">
                <span><i class="icon-upload1"></i>&nbsp;Choose&nbsp;File</span>
                <input id="fileImage_@Model.hdnImageName" name="logo" type="file" class="attachment_upload">
            </div>
        </div>
    </div>
</div>

<div class="modal animated bounce fade text-xs-left" id="Modal_@Model.hdnImageName" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary white">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crop image as per your preference</h4>
            </div>
            <div class="modal-body">
                <div class="img-container" id="dvCrop_@Model.hdnImageName">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick='SaveCropedImage(@Html.Raw(Json.Encode(Model.saveFilePath)),@Html.Raw(Json.Encode(Model.hdnImageName)),"@Url.Action("UploadCropImage", "Utility")");'>Save Crop Image</button>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        var brand = document.getElementById('fileImage_' + @Html.Raw(Json.Encode(Model.hdnImageName)));
        brand.onchange = function () {
            $("#fileFake_" + @Html.Raw(Json.Encode(Model.hdnImageName))).val(this.value.substring(12));
            readURL(this);
        };
        brand.onclick = function () {
            $(this).val('');
        };

        function readURL(input) {
            if (input.files && input.files[0]) {

                var dvCropImage = document.getElementById("dvCrop_" + @Html.Raw(Json.Encode(Model.hdnImageName)));
                dvCropImage.innerHTML = "";

                var reader = new FileReader();

                reader.onload = function (e) {
                    var img = document.createElement("IMG");
                    img.id = "cropimage_" + @Html.Raw(Json.Encode(Model.hdnImageName));
                    img.className = "file-crop";
                    img.src = e.target.result;
                    console.log(img)
                    dvCropImage.appendChild(img);

                };
                reader.readAsDataURL(input.files[0]);

                $("#Modal_" + @Html.Raw(Json.Encode(Model.hdnImageName))).modal({
                    backdrop: 'static',
                    keyboard: false
                }).on('shown.bs.modal',function () {
                        InitilizeImageCrop();
                    });
            }
        }

        function InitilizeImageCrop() {
            $("#loader_" + @Html.Raw(Json.Encode(Model.hdnImageName))).hide()
            $("#cropimage_" + @Html.Raw(Json.Encode(Model.hdnImageName))).cropper({
                autoCropArea: 1,
                //aspectRatio: 1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                viewMode: 2
            });
        }
    });
</script>

Proactive.Admin/Views/Shared/_Summary.cshtml
@model SummaryModel

   
    <tr align="center">
        <td style="padding: 2px !important;">Close</td>
        <td style="padding: 2px !important;">@Model.close</td>
    </tr>
    <tr align="center">
        <td style="padding: 2px !important;">Open</td>
        <td style="padding: 2px !important;">@Model.Open</td>
    </tr>
    <tr align="center">
        <td style="padding: 2px !important;">Pending</td>
        <td style="padding: 2px !important;">@Model.pending</td>
    </tr>
    <tr align="center">
        <td style="padding: 2px !important;">Retracted</td>
        <td >@Model.retracted</td>
    </tr>
    <tr align="center">
        <td style="padding: 2px !important;">Reject</td>
        <td style="padding: 2px !important;">@Model.Rejected</td>
    </tr>
    <tr align="center">
        <td style="padding: 2px !important;">Approved</td>
        <td style="padding: 2px !important;">@Model.Approved</td>
    </tr>
    <tr align="center">
        <td style="padding: 2px !important;"><b>TOTAL</b></td>
        <td style="padding: 2px !important;">@Model.Total</td>
    </tr>
 