Proactive.Admin/Controllers/InsightsTrendsController.cs
using Microsoft.AspNet.Identity;
using Proactive.Admin.Filters;
using Proactive.Core.Enumerations;
using Proactive.Core.Models;
using Proactive.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Proactive.Admin.Controllers
{
    [CustomAuthorization(Role.Admin, Role.Client)]
    public class InsightsTrendsController : ApplicationBaseController
    {
        private readonly InsightsTrendsService _service;
        public InsightsTrendsController()
        {
            _service = new InsightsTrendsService();

        }

        public ActionResult Index()
        {
            return View(_service.GetInsightsTrends());
        }
        public ActionResult IndexByUser()
        {
            var UserId = User.Identity.GetUserId();
            return View(_service.GetInsightsTrends(UserId));
        }

        public ActionResult Add()
        {
            InsightsTrendsModel model = new InsightsTrendsModel();
            using (UserService service = new UserService())
            {
                foreach (var item in service.GetUsers().ToList())
                {
                    model.ClientList.Add(new CheckBoxModel() { Value = item.UserId, Text = item.Name });
                }
            }
            return View("AddorUpdate", model);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int Id)
        {
            BindClient();
            InsightsTrendsModel model = await _service.GetInsightsTrends(Id);
            if (model != null)
            {
                return View("AddorUpdate", model);
            }
            OnBindMessage(AlertStatus.Danger, "Resource can't be found");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Edit(InsightsTrendsModel model)
        {
            BindClient();
            if (ModelState.IsValid)
            {
                ResponseModel<object> mResult = await _service.AddorUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);
                if (mResult.Status == ResponseStatus.Success)
                {
                    return RedirectToAction("Index");
                }
            }
            return View("AddorUpdate", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Add(InsightsTrendsModel model)
        {
            BindClient();
            if (ModelState.IsValid)
            {
                ResponseModel<object> mResult = await _service.AddorUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);
                if (mResult.Status == ResponseStatus.Success)
                {
                    return RedirectToAction("Index");
                }
            }
            return View("AddorUpdate", model);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(int Id)
        {
            ResponseModel<object> mResult = await _service.Delete(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

    }
}

Proactive.Admin/Views/InsightsTrends/AddorUpdate.cshtml
@model InsightsTrendsModel
@{
    ViewBag.Title = ViewBag.Action + "Insights Trend";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string _action = ViewBag.Action;
}
@Styles.Render("~/css/summernote")
@Styles.Render("~/css/icheck")
@Styles.Render("~/css/uploadImage")
<section id="validation">
    <div class="row">
        <div class="col-xs-12">
            @using (Html.BeginForm("Add", "InsightsTrends", FormMethod.Post, new { @id = "frmAddInsights", @class = "form-horizontal" }))
            {
                @Html.HiddenFor(x => x.Id)
                <div class="card box-shadow-0 border-primary">
                    <div class="card-header card-head-inverse bg-primary">
                        <h4 class="card-title">@ViewBag.Action Insights & Trends</h4>
                        <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    </div>
                    <div class="card-body collapse in">
                        <div class="card-block">
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        @Html.Partial("_ImageUpload", new UploadImageModel() { imageUrl = GlobalConfig.BrandImageUrl + Model.imageName, saveFilePath = GlobalConfig.BrandImagePath, hdnImageName = "imageName" })
                                        @Html.HiddenFor(x => x.imageName)
                                        @Html.ValidationMessageFor(x => x.imageName)
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control require", @placeholder = "Enter title here" })
                                        @Html.ValidationMessageFor(x => x.Title)
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <div class="col-md-12" style="align-content:center">
                                            @Html.TextAreaFor(x => x.Description, new { @class = "form-control require", @placeholder = "Enter content here" })
                                            @Html.ValidationMessageFor(x => x.Description)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <input type="submit" class="btn btn-md btn-primary" value="Save Changes" />
                                <a href="@Url.Action("Index")" class="btn btn-md btn-grey">
                                    Cancel
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/validate")
    @Scripts.Render("~/jQuery/iCheck")
    @Scripts.Render("~/jQuery/summernote")
    @Scripts.Render("~/jQuery/uploadImage")
    <script type="text/javascript">
        $(function () {
            $('#Description').summernote({
                height: 200,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: true,
                toolbar: [
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                ],
            });
        });
    </script>

}

Proactive.Admin/Views/InsightsTrends/Index.cshtml
@model IEnumerable<InsightsTrendsModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Manage Insights Trends";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Role UserRole = ViewBag.UserRole;

}

@Styles.Render("~/css/gridMvc")
<style>
    .modal {
    }
</style>
@helper ActionButtons(int Id)
{
    <a href="@Url.Action("Edit", "InsightsTrends", new { @id = Id })" class="btn btn-sm btn-primary btn-blue">
        <i class="icon-edit2"></i> Edit
    </a>
    <a href="javascript:;" class="btn btn-sm btn-primary btn-red deleteData" data-id="@Id">
        <i class="icon-trash-o"></i> Delete
    </a>
}
@helper GetActiveStatus(bool IsActive)
{
if (IsActive)
{
        <span class="text-success">Yes</span>
}
else
{
        <span class="text-danger">No</span>
}
}
@helper BindPopUp(int id, string Descriptipon, string Title)
{
<a href="#" data-toggle="modal" data-target="#@id"
   class="card-link">
   View Insights Trends
</a>
    <div class="modal fade" id="@id" tabindex="-1" role="dialog" aria-labelledby="fp_ModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="fp_ModalLabel">@Title</h5>
                </div>
                <div class="modal-body">
                    @Html.Raw(HttpUtility.HtmlDecode(Descriptipon))
                </div>
            </div>
        </div>
    </div>
}
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card box-shadow-0 border-primary">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">All Insights Trends</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4 white font-size-large"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2 white font-size-large"></i></a></li>
                            @if (UserRole == Role.Admin)
                            {
                                <li class="btn btn-white">
                                    <a href="@Url.Action("Add")" class="primary">
                                        <i class="icon-plus3 primary"></i>&nbsp;Add New
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add(x => x.Title).Titled("Title");
                               column.Add(x => x.Description).Titled("Description").Encoded(false).Sanitized(false).RenderValueAs(x => BindPopUp(x.Id, x.Description, x.Title));
                               //column.Add().Filterable(true).Sortable(true).Encoded(false).Sanitized(false).Titled("View on Web").RenderValueAs(x => GetActiveStatus(x.IsViewOnWeb)).SetWidth(50);
                               if (UserRole == Role.Admin)
                               {
                                   column.Add().Titled("Action").Encoded(false).Sanitized(false)
                                   .RenderValueAs(x => ActionButtons(x.Id)).SetWidth(300);
                               }
                           }).Sortable(true).Filterable(true).Selectable(false).WithPaging(GlobalConfig.PageSize_AdminPanel)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script type="text/javascript">
        ActiveMenu("InsightsTrends");
         $(function () {
            $(".deleteData").click(function () {
                deleteRow($(this), '@Url.Action("Delete")');
            });
        });
         $(document).ready(function () {
         $('.chk-group').iCheck({
             checkboxClass: 'icheckbox_square-purple',
             radioClass: 'iradio_square-purple',
         });
         $('.chk-all').iCheck({
             checkboxClass: 'icheckbox_square-purple',
             radioClass: 'iradio_square-purple',
         });

         $('#select_all').on('ifToggled', function () {
             $(".chk-group").prop('checked', $(this).prop("checked")).iCheck('update');
         })
         $('.chk-group').on('ifUnchecked', function () {
             $("#select_all").prop('checked', false).iCheck('update');
         })
         $('.chk-group').on('ifChecked', function () {
             if ($('.chk-group:checked').length == $('.chk-group').length) {
                 $("#select_all").prop('checked', true).iCheck('update');;
             }
         })
         });
    </script>
}

Proactive.Admin/Views/InsightsTrends/IndexByUser.cshtml
@model IEnumerable<InsightsTrendsModel>
@using GridMvc.Html
@{
    ViewBag.Title = "IndexByUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Role UserRole = ViewBag.UserRole;
}
@helper BindPopUp(int id, string Descriptipon, string Title)
{
    <a href="#" data-toggle="modal" data-target="#@id"
       class="card-link">
        View Insights Trends
    </a>
    <div class="modal fade" id="@id" tabindex="-1" role="dialog" aria-labelledby="fp_ModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="fp_ModalLabel">@Title</h5>
                </div>
                <div class="modal-body">
                    @Html.Raw(HttpUtility.HtmlDecode(Descriptipon))
                </div>
            </div>
        </div>
    </div>
}


<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card box-shadow-0 border-primary">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">All Insights Trends</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4 white font-size-large"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2 white font-size-large"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add(x => x.Title).Titled("Title");
                               column.Add(x => x.Description).Titled("Description").Encoded(false).Sanitized(false).RenderValueAs(x => BindPopUp(x.Id, x.Description, x.Title));
                           }).Sortable(true).Filterable(true).Selectable(false).WithPaging(GlobalConfig.PageSize_AdminPanel)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {

}