Proactive.Admin/Controllers/SellerController.cs
using Microsoft.AspNet.Identity;
using Proactive.Admin.Filters;
using Proactive.Core.Enumerations;
using Proactive.Core.Models;
using Proactive.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Proactive.Admin.Controllers
{
    [CustomAuthorization(Role.Admin, Role.Client)]
    public class SellerController : ApplicationBaseController
    {
        // GET: Seller
        private readonly SellerServices _service;
        public SellerController()
        {
            _service = new SellerServices();
        }

        public ActionResult Index()
        {
            ViewBag.action = "Add";
            List<GetSellerListModel> model = _service.GetAllSellers();
            return View(model);
        }

        public ActionResult RepeatedInfregment()
        {
            string userid = User.Identity.GetUserId();
            List<GetRepeatedInfregment> model = _service.GetRepeatedInfregment(userid);
            return View(model);
        }

        //[HttpPost]
        //public Task<JsonResult> RepeatedInfregments(DataTableAjaxPostModel model)
        //{
        //    DataTableAjaxResultModel result = await _service.GetFilteringList(model);
        //    return Json(result);
        //}

        public ActionResult Add()
        {
            ViewBag.action = "Add";
            return View("AddOrUpdate");
        }

        [HttpPost]
        public async Task<ActionResult> Add(AddSellerModel model)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            if(ModelState.IsValid)
            {
                mResult = await _service.AddUpdateSeller(model);

            }
            if(mResult.Status==ResponseStatus.Success)
            {
                OnBindMessage(AlertStatus.Success, mResult.Message);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            ViewBag.action = "Edit";
            AddSellerModel model = await _service.GetSellerDetail(id);
            if (model == null)
                return RedirectToActionPermanent("Index");
            return View("AddorUpdate", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(AddSellerModel model)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            if (ModelState.IsValid)
            {

                mResult = await _service.AddUpdateSeller(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");
            }
            return View("AddorUpdate", model);
        }

        public async Task<JsonResult> Delete(long Id)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            mResult = await _service.Delete(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }
    }
}

Proactive.Admin/Views/Seller/Index.cshtml
@model List<GetSellerListModel>
@using GridMvc.Html
@{
    string _action = ViewBag.action;
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")

@helper ActionButtons(int sellerId)
{
    <a href="@Url.Action("Edit","Seller",new { @id= sellerId })" class="btn btn-sm btn-primary btn-blue">
        <i class="icon-edit2"></i> Edit
    </a>


    <a href="javascript:;" class="btn btn-sm btn-primary btn-red deleteData" data-id="@sellerId">
        <i class="icon-trash-o"></i> Delete
    </a>
}

@helper ViewChart(int userId, string Name)
{
    @Name
    <br />

}

@helper Contact(int userId, string Name)
{
    @Name
    <br />

}

@helper LinkedList(List<SellerAccountsList> list)
{
    <ul>
        @foreach (var itm in list)
        {
            <li>@itm.LinkedAccName</li>
        }
    </ul>
}

@helper Highrisk(List<SellerHighriskAccList> list)
{
    <ul>
        @foreach (var itm in list)
        {
            <li>@itm.HighriskAccName</li>
        }
    </ul>
}

<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card box-shadow-0 border-primary">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">View Sellers</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4 white font-size-large"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2 white font-size-large"></i></a></li>
                            <li class="btn btn-white">
                                <a href="@Url.Action(_action,"Seller")" class="primary">
                                    <i class="icon-plus3 primary"></i>&nbsp;Add New
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                                {
                                    column.Add(t => t.Name).Titled("Name").Encoded(false).Sanitized(false)
                                     .RenderValueAs(x => ViewChart(x.SellerId, x.Name));

                                    column.Add(t => t.Contact).Titled("Contact").Encoded(false).Sanitized(false)
                                     .RenderValueAs(x => Contact(x.SellerId, x.Contact));

                                    column.Add(t => t.SellerAccounts).Titled("Linked Account").Encoded(false).Sanitized(false)
                                     .RenderValueAs(x => LinkedList(x.SellerAccounts));

                                    column.Add(t => t.SellerHighriskAccList).Titled("Highrisk Account").Encoded(false).Sanitized(false).RenderValueAs(x => Highrisk(x.SellerHighriskAccList));

                                    column.Add().Titled("Action").Encoded(false).Sanitized(false)
                                    .RenderValueAs(x => ActionButtons(x.SellerId));

                                }).Sortable(true).Filterable(true).Selectable(false).WithPaging(GlobalConfig.PageSize_AdminPanel)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script src="~/Content/Jquery/scripts.js"></script>
    <script type="text/javascript">
        ActiveMenu("Sellers");
         $(function () {
            $(".deleteData").click(function () {
                deleteRows($(this), '@Url.Action("Delete")');
            });
        });

        function deleteRows(control, Url) {
            control.children('i').removeClass('icon-trash-o').addClass('icon-spinner10 spinner');
            swal({
                title: "Are you sure to delete this record?",
                text: "You will not be able to recover this date!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DA4453",
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "No, cancel plx!",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                if (isConfirm) {
                    $.post(Url, { 'id': $(control).attr('data-id') }, function (response) {
                        console.log(response);
                        if (response.Status==1) {
                            console.log('success');
                            control.parent().parent().hide();
                            setTimeout(function () { control.remove() }, 300);
                            swal("Deleted!", response.Message, "success");
                        }
                        else {
                            console.log('Failed');
                            control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-trash-o');
                            swal("Error", response.Message, "error");
                        }
                    });
                } else {
                    control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-trash-o');
                    swal("Cancelled", "Your record is safe :)", "info");
                }
            });
        }


    </script>
}

Proactive.Admin/Views/Seller/RepeatedInfregment.cshtml
@model List<GetRepeatedInfregment>
@using GridMvc.Html
@{
    ViewBag.Title = "RepeatedInfregment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")

@helper ViewName(int? sellerid, string Name)
{
    @Name
}

@helper ViewContactDetail(string contact)
{
    @contact
}

@helper viewPlatform(string platform, string site)
{
    @platform
    <br />
    @site
}

@helper ViewCount(int count)
{
    @count
}



@helper LinkedList(List<SellerAccountsList> list)
{
    <ul>
        @foreach (var itm in list)
        {
            <li>@itm.LinkedAccName</li>
        }
    </ul>
}

@helper Highrisk(List<SellerHighriskAccList> list)
{
    <ul>
        @foreach (var itm in list)
        {
            <li>@itm.HighriskAccName</li>
        }
    </ul>
}
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card box-shadow-0 border-primary">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">Repeated Infregment</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4 white font-size-large"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2 white font-size-large"></i></a></li> 
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add(t => t.PlateForm).Titled(Html.Raw("Plateform <br/><hr> Site").ToString()).Encoded(false).Sanitized(false)
                                .RenderValueAs(x => viewPlatform(x.PlateForm, x.Country));

                               column.Add(t => t.Name).Titled("Name").Encoded(false).Sanitized(false)
                                .RenderValueAs(x => ViewName(x.SellerId, x.Name));

                               column.Add(t => t.ContactDetail).Titled("Contact Detail").Encoded(false).Sanitized(false)
                                .RenderValueAs(x => ViewContactDetail(x.ContactDetail));

                               column.Add(t => t.SellerAccounts).Titled("Linked Account").Encoded(false).Sanitized(false)
                                .RenderValueAs(x => LinkedList(x.SellerAccounts));

                               column.Add(t => t.SellerHighriskAccList).Titled("Highrisk Account").Encoded(false).Sanitized(false).RenderValueAs(x => Highrisk(x.SellerHighriskAccList));

                               column.Add(t => t.Count).Titled("Count").Encoded(false).Sanitized(false)
                                .RenderValueAs(x => ViewCount(x.Count));

                           }).Sortable(true).Filterable(true).Selectable(false).WithPaging(GlobalConfig.PageSize_AdminPanel)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script src="~/Content/Jquery/scripts.js"></script>
    <script type="text/javascript">
        ActiveMenu("RepeatedInfregment");



    </script>
}